services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: AnythingLLM
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="6e8192db-3116-4294-be5d-d7bdef91b328"
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://10.10.1.61:11434
      - OLLAMA_MODEL_PREF=llama3.2:latest
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - OLLAMA_PERFORMANCE_MODE=base
      - OLLAMA_KEEP_ALIVE_TIMEOUT=300
      - EMBEDDING_ENGINE=native
      - VECTOR_DB=lancedb
    volumes:
      - anythingllm_storage:/app/server/storage
    restart: always

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/anythingllm
