services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    network_mode: bridge
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      - TZ=America/Bogota
      - HOST_CONTAINERNAME=calibre
      - PASSWORD=161230
      - CLI_ARGS=
      - PUID=99
      - PGID=100
      - UMASK=022
    ports:
      - 8081:8080/tcp
      - 8182:8181/tcp
      - 8082:8081/tcp
    volumes:
      - /external/media/:/data:rw
      - /data/calibre:/config:rw
