services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      - TZ=America/Bogota
      - HOST_CONTAINERNAME=cyberchef
    ports:
      - 8000:80/tcp
