services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      - TZ=America/Bogota
      - HOST_OS=Unraid
      - HOST_HOSTNAME=mambru.tower
      - HOST_CONTAINERNAME=navidrome
      - ND_SCANSCHEDULE=1m
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=
      - ND_IMAGECACHESIZE=200MB
    ports:
      - 4533:4533/tcp
    volumes:
      - /data/navidrome:/data:rw
      - /external/media/music/:/music:rw
